---
title: "5_2_Decision Tree"
author: "Choi"
date: "2021년 8월 26일"
output: html_document
---

1. 성장단계 : 적절한 최적의 분리규칙을 찾음
2. 가지치기 단계 : 오차를 크게하거나 부적절한 추론 규칙을 가지고 있는 불필요한 가지 제거, 모형의 복잡도 감소
3. 타당성 평가 단계 :  이익도표, 위험도표 등으로 평가
4. 해석 및 예측 단계

종류
1. CART : 분류에서는 지니계수, 연속형인 경우 분산을 이용해 이진분리(function : rpart)
2. C4.5 C5.0 : 다지 분리가 가능, 엔트로피 지수를 불순도 측도로 사용(function : tree)
3. CHAID : 가지치기를 하지 않고 적당한 크기에서 나무 성장을 중지, 카이제곱 통계량을 불순도 측도로 사용(function : ctree)

```{r setup, include=FALSE}
rm(list=ls())
library(rpart)
library(rpart.plot)
credit <- read.csv('credit_final.csv')
idx <- sample(1:nrow(credit),nrow(credit)*0.7,replace=F)
train <- credit[idx,]
test <- credit[-idx,]
```
```{r}
dt.model <- rpart(credit.rating~.,
                  method='class',      # method takes one of tree types
                  data=train,
                  control = rpart.control(maxdepth=5,     # max depth
                                          minsplit=15))   # samples of each node are at least 15 
prp(dt.model, type=4, extra=2) # plot의 인자와 같음
```

```{r}
dt.model$cptable   # cp :complexity, 교차타당성 오차를 제공
```

```{r}
#가장 낮은 xerror(해당 CP에서 cross validation 했을 때 오류율)를 갖는  split 개수를 선택
opt <- which.min(dt.model$cptable[,"xerror"])   
cp <- dt.model$cptable[opt,"CP"]
prune.c <- prune(dt.model, cp=cp)
plotcp(dt.model)
```

## Checking Performance

```{r}
library(caret)
pred.dt <- predict(dt.model, test[,-1], type='class')
confusionMatrix(pred.dt, as.factor(test[,1]), positive='1')
```
```{r}
library(ROCR)
pred.dt.roc <- prediction(as.numeric(pred.dt), as.numeric(test[,1]))
plot(performance(pred.dt.roc,'tpr','fpr'))
abline(a=0, b=1, lty=2, col='black')
```

```{r}
performance(pred.dt.roc,'auc')@y.values

```

```{r}

```

